databases:
  - name: nora-college
    databaseName: teiritu_production
    user: teiritu
    region: Singapore

services:
  - type: web
    name: nora-college
    env: ruby
    region: Singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://teiritu:gMEcZy41hwD5paHFEvdFfXOpPIwHaXAK@dpg-cnder2acn0vc73f696n0-a/teiritu_production
        fromDatabase:
          name: teiritu_production
          property: connectionString
      - key: 9a52904fe66accb0bf96ef879b024256%
        sync: false